### ISSUE TITLE
Should the axiom library work with Cordova/Apache PhoneGap

### ISSUE THREAD

**Issue by joshglenn** [mzabriskie/axios#414]
I am building a mobile app using PhoneGap. When I debug in the browser, my app works fine using axiom to load the data from a json file. But on the iOS simulator, it is not working. Nor is it throwing an error.

I am using Redux and redux-thunk here also. My trouble is I can't seem to debug this. I have stepped through the code, I don't see any error being thrown.

Any ideas? Or suggestions how to track this down?

Here is the code:

```
export function fetchRemote() {
  return function(dispatch) {
    // get translations http://localhost:8000/
    console.log('About to fetch json')
    axios.get('data/2016-07-13-dictionary.json')
      .then((response) => {
        console.log('Success fetching json')
        dispatch({type: 'FETCH_JSON_FULFILLED', payload: response.data})
      })
      .catch((err) => {
        console.log(err)
        dispatch({type: 'FETCH_JSON_REJECTED', payload: err})
      })
  }
}
```

**Comment by mzabriskie** [comment]
I don't have any PhoneGap experience, so I can't really comment. From what I think I know about PhoneGap though they render using a WebView which should be a sufficient environment for axios to run. I will put this out on the Twittersphere to see if anyone can provide some insight for you.

**Comment by revolunet** [comment]
Hi
It should work
Do you use Safari developer menu to get the simulator console ?

**Comment by joshglenn** [comment]
Yes. I am able to debug the code , but no error is ever returned, nor do either of the "then" blocks get executed.

**Comment by revolunet** [comment]
Do you have a catch block?
Promises have the nasty habit to swallow exceptions

**Comment by revolunet** [comment]
Ha yes you have in your example... Weird
Cordova version ?
Do you use wkwebview ?

**Comment by rubennorte** [comment]
Have you checked in the developer tools if the request is ever sent? Could you copy here the details of the request, if any?

**Comment by joshglenn** [comment]
@revolunet my Cordova version is 5.4.1 according to the `npm list` command. And I'm not familiar with _wkwebview_, so I'm guessing not.

@rubennorte Thanks. It looks like the request is being sent, and data apparently is being returned. However, it looks like a status nothing is coming back in the Status of the response, just a blank dash according to the developer tools.

<img width="1191" alt="screen shot 2016-08-14 at 7 52 16 pm" src="https://cloud.githubusercontent.com/assets/6953274/17653298/e846a948-6258-11e6-9e7e-9ae5f91ce238.png">

**Comment by rubennorte** [comment]
I think the issue is caused by the fact that the `file:` scheme always resolve with `0` as status code. That would explain why it isn't either resolved or rejected according to this part of axios (xhr adapter):

```javascript
// The request errored out and we didn't get a response, this will be
// handled by onerror instead
if (request.status === 0) {
  return;
}
```

After that code the promise is resolved and as `onerror` is never called the promise is never settled.

This is actually an Axios issue that should be addressed.

**Comment by revolunet** [comment]
nice catch @rubennorte https://github.com/mzabriskie/axios/blob/6132d9630d641d253f268c8aa2e128aef94ed44f/lib/adapters/xhr.js#L59

**Comment by nickuraltsev** [comment]
Fixed via #440

**Comment by twoavy-jf** [comment]
this issue came back for me with v0.19.0 fixed it by downgrading to 0.18.0 again.

**Comment by mairasala** [comment]
I'm facing the sam issue with v.1.9.0
