### ISSUE TITLE
can't access to response header fields  although OPTIONS and POST response ok

### ISSUE THREAD

**Issue by naixinxiaozi** [mzabriskie/axios#746]
I'm building a frontend app with Vue2 and I'm using axios to perform my requests. I would like to get access to all the fields in the header of the response. In my browser I can inspect the header and I can see that all the fields that I need are present(such as token, uid, etc...), but when I call

const request = axios.post(`${base}/api/login`, params);
request.then((response)=>{
  console.log(response.headers);
});

I get just
`Object {content-type: "application/json"}`

1.  options request, you can see  Access-Control-Expose-Headers has been set.
![1](https://cloud.githubusercontent.com/assets/12477998/23698724/8ebf241a-0427-11e7-84fc-00d5206b9924.png)
2. post request. The reponse has a header named 'X-Bable-Session'.
![2](https://cloud.githubusercontent.com/assets/12477998/23698759/b6c42b5e-0427-11e7-90e6-37649917e969.png)

3. debug mode in my browser. You can see the response headers only contain 'content-type'.
headers['X-Bable-Session'] is undefined here.

![3](https://cloud.githubusercontent.com/assets/12477998/23698880/2aa1e106-0428-11e7-963b-5c663e2ee93b.png)

`export const requestLogin = params => { return axios.post(`${base}/api/login`, params).then(res=>res); };`

my axios version:  "^0.15.3"
Does someone have same issue?

**Comment by TracyDa** [comment]
same issue,don't understand why axios just can't do this simple basic thing!

the sample code is so easy,but if you try,you got so many problem.

**Comment by naixinxiaozi** [comment]
Hi, it is solved.  The server should add header "Access-Control-Expose-Headers" in POST response.
In my attached images, the header "Access-Control-Expose-Headers" only appears in OPTIONS response. When I submit this issue, I think the header appears in OPTIONS response is enough. But in fact,  the header 
must be alse in **POST POST POST** response.

**Comment by TracyDa** [comment]
@naixinxiaozi  So what's your "Access-Control-Expose-Headers" in response header?I tried ,but still not work.

**Comment by naixinxiaozi** [comment]
It is same with the value in OPTIONS response. You can see from the attached pic.

I think this is just a **workaround**. I plan to opan another isuue

**Comment by naixinxiaozi** [comment]
1. The server returns **Access-Control-Expose-Headers** in OPTION response
2. The POST request returns some headers which user needed

The Client should **cache** OPTIONS respose. According to 'Access-Control-Expose-Headers' to process the POST response headers. If the cache expired after Access-Control-Max-Age, the client should send another OPTIONS request.

I don't know who should be the client, axios or the browers?

**Comment by alfonsodev** [comment]
The problems here is that `axios` kind of shallows the error, 
But, as axios exposes `request : XMLHttpRequest` you can trying to access the 
header directly from the  XMLHTttpRequest object.
```
request.getResponseHeader('X-Request-Id')
```
and then you get the exact error `Refused to get unsafe header "X-Request-Id"`

For people using express and it's cors module, there is a configuration variable called `exposedHeaders`
you can use it like this. 
```
const corsOptions = {
  origin: 'http://localhost:8080',
  allowedHeaders: ['Accept-Version', 'Authorization', 'Credentials', 'Content-Type'],
  exposedHeaders: ['X-Request-Id'],
}

app.all('*', cors(corsOptions))
```
